### ISSUE TITLE
Add Fleet and Rancher Operator to the ResourceSet

### ISSUE THREAD

**Issue by sowmyav27** [rancher/backup-restore-operator#69]
From 2.5.6, fleet/rancher-operator/webhook ~will not be auto upgraded~ will not be upgraded outside of a rancher upgrade to that specific version. So this will have to be included in the resourceset - related issue - https://github.com/rancher/rancher/issues/30934

**Comment by cbron** [comment]
By resourceset, do you mean the backup operator ?

**Comment by nickgerace** [comment]
Dependent issues:

- [ ] Add Fleet to the ResourceSet #71
- [ ] Add Rancher Operator to the ResourceSet #72
- [ ] Add Rancher Webhook to the ResourceSet #73

**Comment by nickgerace** [comment]
**Status**: #71 and #72 have been added to the chart, and the chart has been moved from `rancher/charts` to `rancher/backup-restore-operator`.

Awaiting assignment/prioritization for #73, which requires an operator-level change and was **not** included in the new chart (https://github.com/rancher/backup-restore-operator/releases/tag/v1.0.4-rc2)

**Comment by nickgerace** [comment]
This issue is now only the parent issue for Fleet and Rancher Operator since Webhook requires an operator-level change.

**Comment by nickgerace** [comment]
Since #72 and #71 are closed, this can be as well.
